/* Autogenerated by mlir-tblgen; don't manually edit. */
// clang-format off

#pragma once

#include "Util.h"
#include "proto/attr.pb.h"

#include <clang/CIR/Dialect/IR/CIRAttrs.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/Location.h>

using namespace protocir;

class AttributeSerializer {
public:
  AttributeSerializer(MLIRModuleID moduleID, TypeCache &typeCache)
      : moduleID(moduleID), typeCache(typeCache) {}

  MLIRAttribute serializeMLIRAttribute(mlir::Attribute);

  MLIRArrayAttr serializeMLIRArrayAttr(mlir::ArrayAttr);
  MLIRDictionaryAttr serializeMLIRDictionaryAttr(mlir::DictionaryAttr);
  MLIRFloatAttr serializeMLIRFloatAttr(mlir::FloatAttr);
  MLIRIntegerAttr serializeMLIRIntegerAttr(mlir::IntegerAttr);
  MLIRStringAttr serializeMLIRStringAttr(mlir::StringAttr);
  MLIRTypeAttr serializeMLIRTypeAttr(mlir::TypeAttr);
  MLIRUnitAttr serializeMLIRUnitAttr(mlir::UnitAttr);
  MLIRNamedAttr serializeMLIRNamedAttr(mlir::NamedAttribute);
  MLIRFlatSymbolRefAttr serializeMLIRFlatSymbolRefAttr(mlir::FlatSymbolRefAttr);
  MLIRDenseI32ArrayAttr serializeMLIRDenseI32ArrayAttr(mlir::DenseI32ArrayAttr);

  MLIRLocation serializeMLIRLocation(mlir::Location);

  MLIRCallSiteLoc serializeMLIRCallSiteLoc(mlir::CallSiteLoc);
  MLIRFileLineColLoc serializeMLIRFileLineColLoc(mlir::FileLineColLoc);
  MLIRFusedLoc serializeMLIRFusedLoc(mlir::FusedLoc);
  MLIRNameLoc serializeMLIRNameLoc(mlir::NameLoc);
  MLIROpaqueLoc serializeMLIROpaqueLoc(mlir::OpaqueLoc);
  MLIRUnknownLoc serializeMLIRUnknownLoc(mlir::UnknownLoc);

  CIRAddressSpaceAttr serializeCIRAddressSpaceAttr(cir::AddressSpaceAttr);
  CIRAnnotationAttr serializeCIRAnnotationAttr(cir::AnnotationAttr);
  CIRBitfieldInfoAttr serializeCIRBitfieldInfoAttr(cir::BitfieldInfoAttr);
  CIRBoolAttr serializeCIRBoolAttr(cir::BoolAttr);
  CIRTBAAAttr serializeCIRTBAAAttr(cir::TBAAAttr);
  CIRCatchAllAttr serializeCIRCatchAllAttr(cir::CatchAllAttr);
  CIRCatchUnwindAttr serializeCIRCatchUnwindAttr(cir::CatchUnwindAttr);
  CIRCmpThreeWayInfoAttr serializeCIRCmpThreeWayInfoAttr(cir::CmpThreeWayInfoAttr);
  CIRComplexAttr serializeCIRComplexAttr(cir::ComplexAttr);
  CIRConstArrayAttr serializeCIRConstArrayAttr(cir::ConstArrayAttr);
  CIRConstPtrAttr serializeCIRConstPtrAttr(cir::ConstPtrAttr);
  CIRConstStructAttr serializeCIRConstStructAttr(cir::ConstStructAttr);
  CIRConstVectorAttr serializeCIRConstVectorAttr(cir::ConstVectorAttr);
  CIRConvergentAttr serializeCIRConvergentAttr(cir::ConvergentAttr);
  CIRDataMemberAttr serializeCIRDataMemberAttr(cir::DataMemberAttr);
  CIRDynamicCastInfoAttr serializeCIRDynamicCastInfoAttr(cir::DynamicCastInfoAttr);
  CIRExtraFuncAttributesAttr serializeCIRExtraFuncAttributesAttr(cir::ExtraFuncAttributesAttr);
  CIRFPAttr serializeCIRFPAttr(cir::FPAttr);
  CIRGlobalAnnotationValuesAttr serializeCIRGlobalAnnotationValuesAttr(cir::GlobalAnnotationValuesAttr);
  CIRGlobalCtorAttr serializeCIRGlobalCtorAttr(cir::GlobalCtorAttr);
  CIRGlobalDtorAttr serializeCIRGlobalDtorAttr(cir::GlobalDtorAttr);
  CIRGlobalViewAttr serializeCIRGlobalViewAttr(cir::GlobalViewAttr);
  CIRInactiveUnionFieldAttr serializeCIRInactiveUnionFieldAttr(cir::InactiveUnionFieldAttr);
  CIRInlineAttr serializeCIRInlineAttr(cir::InlineAttr);
  CIRIntAttr serializeCIRIntAttr(cir::IntAttr);
  CIRLangAttr serializeCIRLangAttr(cir::LangAttr);
  CIRMethodAttr serializeCIRMethodAttr(cir::MethodAttr);
  CIRNoThrowAttr serializeCIRNoThrowAttr(cir::NoThrowAttr);
  CIROpenCLKernelArgMetadataAttr serializeCIROpenCLKernelArgMetadataAttr(cir::OpenCLKernelArgMetadataAttr);
  CIROpenCLKernelAttr serializeCIROpenCLKernelAttr(cir::OpenCLKernelAttr);
  CIROpenCLKernelMetadataAttr serializeCIROpenCLKernelMetadataAttr(cir::OpenCLKernelMetadataAttr);
  CIROpenCLKernelUniformWorkGroupSizeAttr serializeCIROpenCLKernelUniformWorkGroupSizeAttr(cir::OpenCLKernelUniformWorkGroupSizeAttr);
  CIROpenCLVersionAttr serializeCIROpenCLVersionAttr(cir::OpenCLVersionAttr);
  CIROptNoneAttr serializeCIROptNoneAttr(cir::OptNoneAttr);
  CIRStructLayoutAttr serializeCIRStructLayoutAttr(cir::StructLayoutAttr);
  CIRTypeInfoAttr serializeCIRTypeInfoAttr(cir::TypeInfoAttr);
  CIRUndefAttr serializeCIRUndefAttr(cir::UndefAttr);
  CIRVTableAttr serializeCIRVTableAttr(cir::VTableAttr);
  CIRVisibilityAttr serializeCIRVisibilityAttr(cir::VisibilityAttr);
  CIRZeroAttr serializeCIRZeroAttr(cir::ZeroAttr);

  CIRAsmFlavorAttr serializeCIRAsmFlavorAttr(cir::AsmFlavorAttr);
  CIRAtomicFetchKindAttr serializeCIRAtomicFetchKindAttr(cir::AtomicFetchKindAttr);
  CIRAwaitKindAttr serializeCIRAwaitKindAttr(cir::AwaitKindAttr);
  CIRBinOpKindAttr serializeCIRBinOpKindAttr(cir::BinOpKindAttr);
  CIRBinOpOverflowKindAttr serializeCIRBinOpOverflowKindAttr(cir::BinOpOverflowKindAttr);
  CIRCallingConvAttr serializeCIRCallingConvAttr(cir::CallingConvAttr);
  CIRCaseOpKindAttr serializeCIRCaseOpKindAttr(cir::CaseOpKindAttr);
  CIRCastKindAttr serializeCIRCastKindAttr(cir::CastKindAttr);
  CIRCatchParamKindAttr serializeCIRCatchParamKindAttr(cir::CatchParamKindAttr);
  CIRCmpOpKindAttr serializeCIRCmpOpKindAttr(cir::CmpOpKindAttr);
  CIRCmpOrderingAttr serializeCIRCmpOrderingAttr(cir::CmpOrderingAttr);
  CIRComplexBinOpKindAttr serializeCIRComplexBinOpKindAttr(cir::ComplexBinOpKindAttr);
  CIRComplexRangeKindAttr serializeCIRComplexRangeKindAttr(cir::ComplexRangeKindAttr);
  CIRDynamicCastKindAttr serializeCIRDynamicCastKindAttr(cir::DynamicCastKindAttr);
  CIRGlobalLinkageKindAttr serializeCIRGlobalLinkageKindAttr(cir::GlobalLinkageKindAttr);
  CIRInlineKindAttr serializeCIRInlineKindAttr(cir::InlineKindAttr);
  CIRMemOrderAttr serializeCIRMemOrderAttr(cir::MemOrderAttr);
  CIRSignedOverflowBehaviorAttr serializeCIRSignedOverflowBehaviorAttr(cir::SignedOverflowBehaviorAttr);
  CIRSizeInfoTypeAttr serializeCIRSizeInfoTypeAttr(cir::SizeInfoTypeAttr);
  CIRSourceLanguageAttr serializeCIRSourceLanguageAttr(cir::SourceLanguageAttr);
  CIRTLSModelAttr serializeCIRTLSModelAttr(cir::TLS_ModelAttr);
  CIRUnaryOpKindAttr serializeCIRUnaryOpKindAttr(cir::UnaryOpKindAttr);
  CIRVisibilityKindAttr serializeCIRVisibilityKindAttr(cir::VisibilityKindAttr);

private:
  MLIRModuleID moduleID;
  TypeCache &typeCache;
};

// clang-format on
