name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1,4'
  workflow_call:

jobs:
  get-clangir-id:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read JSON
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./.github/workflows/clangir-version.json)" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  cmp-tblgen-files:
    needs: [get-clangir-id, build]
    strategy:
      matrix:
        clangir: ${{ fromJSON(needs.get-clangir-id.outputs.matrix) }}
    uses: ./.github/workflows/tblgen-check.yml
    with:
      CLANGIR_REPOSITORY: ${{ matrix.clangir.organization }}/${{ matrix.clangir.repository }}
      CLANGIR_VERSION: ${{ matrix.clangir.version }}

  run-gsac-tests:
    needs: [get-clangir-id, build, cmp-tblgen-files]
    strategy:
      matrix:
        clangir: ${{ fromJSON(needs.get-clangir-id.outputs.matrix) }}
    uses: ./.github/workflows/run-test-suite.yml
    with:
      CLANGIR_REPOSITORY: ${{ matrix.clangir.organization }}/${{ matrix.clangir.repository }}
      CLANGIR_VERSION: ${{ matrix.clangir.version }}
      TEST_REPOSITORY: "explyt/GSAC"
      TEST_COMMIT: "macos_version"

  run-juliet-tests:
    if: github.event_name == 'workflow_dispatch'
    needs: [get-clangir-id, build, cmp-tblgen-files]
    strategy:
      matrix:
        clangir: ${{ fromJSON(needs.get-clangir-id.outputs.matrix) }}
    uses: ./.github/workflows/run-test-suite.yml
    with:
      CLANGIR_REPOSITORY: ${{ matrix.clangir.organization }}/${{ matrix.clangir.repository }}
      CLANGIR_VERSION: ${{ matrix.clangir.version }}
      TEST_REPOSITORY: "explyt/juliet-c"
      TEST_COMMIT: "full-flat"
      SEARCH_FOR_CIR: true
