name: 'Release'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'debug'

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    name: 'Release'
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Debug'
        run: |
          printenv

      - name: 'Install and Configure applications'
        run: |
          sudo apt-get update
          sudo apt-get install -yqq --no-install-recommends \
            ca-certificates \
            git-core

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Add git path to trusted'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts

      - name: Compress release files
        working-directory: ${{ github.workspace }}/artifacts
        run: |
          chmod -R +x cir-tac-macos-latest-ARM64
          chmod -R +x cir-tac-ubuntu-latest-X64
          chmod -R +x cir-tac-ubuntu-20.04-X64
          tar -czvf cir-tac-macos-latest-ARM64.tar.gz -C cir-tac-macos-latest-ARM64 *
          tar -czvf cir-tac-ubuntu-latest-X64.tar.gz -C cir-tac-ubuntu-latest-X64 *
          tar -czvf cir-tac-ubuntu-20.04-X64.tar.gz -C cir-tac-ubuntu-20.04-X64 *

      - name: 'Release'
        if: ${{ github.event_name == 'push' }}
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@7.0.2

      - name: 'Pre-Release'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || 'debug'}}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            LICENSE
            ${{ github.workspace }}/artifacts/*

      - name: 'Get release_version and pass to next job'
        id: release_version
        # see .releaserc.json to obtain certain file name
        run: |
          echo "RELEASE_VERSION=$(cat release_version.txt)" >> $GITHUB_OUTPUT

    outputs:
      release_version: ${{ steps.release_version.outputs.RELEASE_VERSION }}
